plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.hanzodev1375.codesnap'
    compileSdk 36

    defaultConfig {
        applicationId 'ir.hanzodev1375.codesnap'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    compileOnly files('libs/editor-sora-0.24.6.jar')
}
